services:
  my-spring-container-oidc:
    container_name: my-spring-container-oidc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network
  mysql-container-oidc:
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: temp_db
    ports:
      - "3307:3306"
    container_name: mysql-container-oidc
    image: mysql:latest
    volumes:
      - mysql-container-oidc-data:/var/lib/mysql
    networks:
      - my-network
volumes:
  mysql-container-oidc-data:
networks:
  my-network:
    external: true